### PR TITLE
Add /-/dist-tags endpoints

### PR DESCRIPTION
**Pull request by isaacs**
For managing dist-tags explicitly

GET /-/package/:pkg/dist-tags -- returns the package's dist-tags
PUT /-/package/:pkg/dist-tags -- Set package's dist-tags to provided object body (removing missing)
POST /-/package/:pkg/dist-tags -- Add/modify dist-tags from provided object body (merge)
PUT /-/package/:pkg/dist-tags/:tag -- Set package's dist-tags[tag] to provided string body
POST /-/package/:pkg/dist-tags/:tag -- Same as PUT /-/package/:pkg/dist-tags/:tag
DELETE /-/package/:pkg/dist-tags/:tag -- Remove tag from dist-tags

### CODE REVIEW

**Comment by isaacs** [comment]
Updated to change url styles to be more restful and thus relaxing.

**Comment by othiym23** [comment]
(I updated the description to match the current set of routes.)

**Comment by othiym23** [comment]
LGTM!

**Comment by fengmk2** [comment]
http://registry.npmjs.com/-/package/npm/dist-tags

**Comment by othiym23** [comment]
The title of the issue reflects @isaacs's original design, but the body reflects what he actually shipped, @fengmk2. ;)

**Comment by fengmk2** [comment]
@othiym23 I will follow the source codes.

**Comment by zeke** [comment]
follow the source codes!

**Pull request merged**
